language: python

sudo: false

env:
  - TOX_ENV=flake8
  # Django 1.11
  - TOX_ENV=py27-dj111-cms35
  - TOX_ENV=py35-dj111-cms35
  # Django 2.0
  - TOX_ENV=py35-dj20-cms35
  - TOX_ENV=py35-dj20-cms40
  # Django 2.1
  - TOX_ENV=py35-dj21-cms35
  - TOX_ENV=py35-dj21-cms40

install:
  - pip install tox coverage

script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)
