[tox]
requires =
    tox>=4.2
envlist =
    ruff
    dj42_cms311
    dj42_cms41
    dj50_cms41
    dj51_cms41
    dj52_cms50
    dj60_cms50
skip_missing_interpreters=True

[testenv]
deps =
    -r tests/requirements/{envname}.txt
commands =
    coverage erase
    coverage run -m pytest
    coverage report -m

[testenv:ruff]
deps = ruff
commands = ruff check djangocms_video
skip_install = true
