# Generated by Django 5.0.9 on 2024-11-30 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('djangocms_video', '0011_alter_videoplayer_cmsplugin_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HlsStreamSource',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('hls_source_url', models.CharField(max_length=1024, verbose_name='HLS Source URL')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
