# Generated by Django 5.0.9 on 2024-11-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_video', '0012_hlsstreamsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoplayer',
            name='autoplay',
            field=models.BooleanField(default=False, help_text='If enabled, the video will automatically play once the page is loaded. This might not work depending on how the user has configured their browser.', verbose_name='Autoplay'),
        ),
        migrations.AddField(
            model_name='videoplayer',
            name='show_controls',
            field=models.BooleanField(default=True, help_text='If enabled, the video will be shown with Play, Pause and Seek elements that allow the user to control playback.', verbose_name='Show controls'),
        ),
    ]
